version: "3.9"
services:
  app:
    build: ./docker/app
    volumes:
      - tmp_target:/tmp/target
      - .:/app
    ports: 
      - 80:8080
    env_file:
      - .env
    tty: true

volumes:
  tmp_target:
